// Generated by https://quicktype.io

export interface User {
  id:                  number;
  login:               string;
  avatar_url:          string;
  name:                string;
  bio:                 string;
}
